title: icyphox's blog
header: |
    <a href=/>
    <img class="logo" src="/static/white.svg" alt="icyphox's avatar"/>
    </a>
    <nav>
    <a href="/">blog</a>
    &middot;
    <a href="/wiki">wiki</a>
    </nav>

siteurl: "https://icyphox.sh"
rssprefixurl: "https://icyphox.sh/blog/" 
description: "Computers, security and computer security."
datefmt: "02 Jan, 2006"
author: 
     name: "Anirudh Oppiliappan"
     email: "x@icyphox.sh"
syntax: 'bw'
footer: |
    <section class="icons">
        <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">
        <img class="footimgs" alt="cc nc-by-sa" src="/static/cc.svg">
        </a>
        <a href="https://webring.xxiivv.com/#random" target="_blank">
        <img class="footimgs" alt="xxiivv webring" src="/static/webring.svg">
        </a>
        <a href="/blog/feed.xml" >
        <img class="footimgs" alt="rss feed" src="/static/rss.svg">
        </a>
    </section>


prebuild:
  - bin/wiki.sh
postbuild:
    # - bin/plaintext.sh

