title: icyphox's blog
header: | 
    <section class="hero">
    <a href=/>
    <img class="logo" src="/static/white.svg" alt="icyphox's avatar"/>
    </a>
    </section>
siteurl: "https://icyphox.sh"
rssprefixurl: "https://icyphox.sh/blog/" 
description: "Computers, security and computer security."
datefmt: "02 January, 2006"
author: 
     name: "Anirudh Oppiliappan"
     email: "x@icyphox.sh"
footer: |
    <hr>
    <section>
        <p>
        <a href="/about">about</a>
        &middot;
        <a href="/uses">uses</a>
        &middot;
        <a href="/friends">friends</a>
        </p>
    </section>
    <section class="icons">
        <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">
        <img class="footimgs" alt="cc nc-by-sa" src="/static/cc.svg">
        </a>
        <a href="https://webring.xxiivv.com/#random" target="_blank">
        <img class="footimgs" alt="xxiivv webring" src="/static/webring.svg">
        </a>
        <a href="/blog/feed.xml" >
        <img class="footimgs" alt="rss feed" src="/static/rss.svg">
        </a>
    </section>


prebuild:
    # - bin/update_index.py
postbuild:
    # - bin/plaintext.sh
