title: Anirudh Oppiliappan
# note the trailing slash!
url: "https://anirudh.fi/"
description: ""
author:
     name: "Anirudh Oppiliappan"
     email: "anirudh@oppiliappan.com"
defaultTemplate: text.html
