title: icyphox's blog
header: | 
    <section class="hero">
    <a href=/>
    <img class="logo" src="/static/white.svg" alt="icyphox's avatar"/>
    </a>
    </section>
siteurl: "https://icyphox.sh"
rssprefixurl: "https://icyphox.sh/blog/" 
description: "Computers, security and computer security."
datefmt: "02 January, 2006"
author: 
     name: "Anirudh Oppiliappan"
     email: "x@icyphox.sh"
footer: |
    <!--<p>
    <span class="sidebar-link">email</span>
    <br>
      <a href="mailto:x@icyphox.sh">x@icyphox.sh</a>
    </p> 

    <p>
    <span class="sidebar-link">git</span>
    <br>
    <a href="https://git.icyphox.sh">git.icyphox.sh</a>
    </p> 

    <p>
    <span class="sidebar-link">fediverse</span>
    <br>
    <a rel="me" href="https://toot.icyphox.sh/@x">@x@toot.icyphox.sh</a>
    </p> 

    <p>
    <span class="sidebar-link">pgp</span>
    <br>
      <a href="/static/gpg.txt">0x8A93F96F78C5D4C4</a>
    </p> 

    -->

    <hr>
    <section>
        <p>
        <a href="/about">about</a>
        &middot;
        <a href="/uses">uses</a>
        &middot;
        <a href="/friends">friends</a>
        </p>
    </section>
    <section class="icons">
        <a href="https://creativecommons.org/licensjes/by-nc-sa/4.0/">
        <img class="footimgs" alt="cc nc-by-sa" src="/static/cc.svg">
        </a>
        <a href="https://webring.xxiivv.com/#random" target="_blank">
        <img class="footimgs" alt="xxiivv webring" src="/static/webring.svg">
        </a>
        <a href="/blog/feed.xml" >
        <img class="footimgs" alt="rss feed" src="/static/rss.svg">
        </a>
    </section>


prebuild:
    # - bin/update_index.py
postbuild:
    # - bin/plaintext.sh
